import asyncio
import os
from typing import Any

import dotenv
from github import Github
from llama_index.core.agent.workflow import (
    AgentOutput,
    AgentWorkflow,
    FunctionAgent,
    ToolCall,
    ToolCallResult,
)
from llama_index.core.prompts import RichPromptTemplate
from llama_index.core.tools import FunctionTool
from llama_index.core.workflow import Context
from llama_index.llms.openai import OpenAI

dotenv.load_dotenv()

llm = OpenAI(
    model="gpt-4o-mini",
    api_key=os.getenv("OPENAI_API_KEY"),
    api_base=os.getenv("OPENAI_BASE_URL"),
)

git = Github(os.getenv("GITHUB_TOKEN")) if os.getenv("GITHUB_TOKEN") else Github()

# GitHub Actions passes the repo as "username/repo-name" via env var REPOSITORY
repository = os.getenv("REPOSITORY", "")
pr_number = os.getenv("PR_NUMBER", "")

repo = git.get_repo(repository) if repository else None


# ── Funciones de herramientas (GitHub) ───────────────────────────

def get_pr_details(pr_number: int) -> dict[str, Any]:
    """Fetch pull request details given the PR number.
    Returns author, title, body, diff_url, state, and commit SHAs."""
    pr = repo.get_pull(int(pr_number))

    commit_shas = []
    for c in pr.get_commits():
        commit_shas.append(c.sha)

    return {
        "user": pr.user.login,
        "title": pr.title,
        "body": pr.body,
        "diff_url": pr.diff_url,
        "state": pr.state,
        "head_sha": commit_shas[-1] if commit_shas else None,
        "commit_shas": commit_shas,
    }


def get_file_content(file_path: str) -> str:
    """Fetch the contents of a file from the repository given its path."""
    content = repo.get_contents(file_path)
    return content.decoded_content.decode("utf-8")


def get_pr_commit_details(head_sha: str) -> list[dict[str, Any]]:
    """Fetch commit details given a commit SHA.
    Returns a list of changed files with filename, status, additions,
    deletions, changes, and patch."""
    commit = repo.get_commit(head_sha)
    changed_files: list[dict[str, Any]] = []
    for f in commit.files:
        changed_files.append(
            {
                "filename": f.filename,
                "status": f.status,
                "additions": f.additions,
                "deletions": f.deletions,
                "changes": f.changes,
                "patch": f.patch,
            }
        )
    return changed_files


# ── Funciones de gestión de estado ───────────────────────────────

async def add_context_to_state(ctx: Context, gathered_contexts: str) -> str:
    """Save the context gathered by the ContextAgent into the shared state."""
    current_state = await ctx.store.get("state")
    current_state["gathered_contexts"] = gathered_contexts
    await ctx.store.set("state", current_state)
    return "Context saved to state."


async def add_comment_to_state(ctx: Context, review_comment: str) -> str:
    """Save the draft PR review comment generated by the CommentorAgent into the shared state."""
    current_state = await ctx.store.get("state")
    current_state["review_comment"] = review_comment
    await ctx.store.set("state", current_state)
    return "Review comment saved to state."


async def add_final_review_to_state(ctx: Context, final_review: str) -> str:
    """Save the final review produced by the ReviewAndPostingAgent into the shared state."""
    current_state = await ctx.store.get("state")
    current_state["final_review"] = final_review
    await ctx.store.set("state", current_state)
    return "Final review saved to state."


def post_review_to_github(pr_number: int, comment: str) -> str:
    """Post a review comment to a GitHub pull request.
    Uses pr.create_review() with event='COMMENT' so the review is submitted
    immediately (not left in pending/draft state)."""
    pr = repo.get_pull(int(pr_number))
    review = pr.create_review(body=comment, event="COMMENT")
    return f"Review posted to PR #{pr_number} (review id: {review.id})."


# ── Tools ───────────────────────────────────────────────────────

pr_details_tool = FunctionTool.from_defaults(get_pr_details)
file_content_tool = FunctionTool.from_defaults(get_file_content)
commit_details_tool = FunctionTool.from_defaults(get_pr_commit_details)
add_context_tool = FunctionTool.from_defaults(fn=add_context_to_state)
add_comment_tool = FunctionTool.from_defaults(fn=add_comment_to_state)
add_final_review_tool = FunctionTool.from_defaults(fn=add_final_review_to_state)
post_review_tool = FunctionTool.from_defaults(fn=post_review_to_github)


# ── ContextAgent ────────────────────────────────────────────────

CONTEXT_SYSTEM_PROMPT = (
    "You are the context gathering agent. When gathering context, you MUST gather \n: "
    "  - The details: author, title, body, diff_url, state, and head_sha; \n"
    "  - Changed files; \n"
    "  - Any requested for files; \n"
    "Once you gather the requested info, you MUST hand control back to the Commentor Agent."
)

context_agent = FunctionAgent(
    llm=llm,
    name="ContextAgent",
    description="Gathers all the needed context from the GitHub repository: PR details, "
                "changed files, commit information, and any additional files requested.",
    tools=[pr_details_tool, file_content_tool, commit_details_tool, add_context_tool],
    system_prompt=CONTEXT_SYSTEM_PROMPT,
    can_handoff_to=["CommentorAgent"],
)


# ── CommentorAgent ──────────────────────────────────────────────

COMMENTOR_SYSTEM_PROMPT = (
    "You are the commentor agent that writes review comments for pull requests as a human reviewer would. \n"
    "IMPORTANT: You must NEVER ask the user for any information. Instead, you MUST hand off to the "
    "ContextAgent to retrieve the PR details, changed files, and any other repo files you need. \n"
    "Ensure to do the following for a thorough review: \n"
    " - ALWAYS start by handing off to the ContextAgent to gather the PR details, changed files, "
    "and any other repo files you may need. Do not ask the user. \n"
    " - Once the ContextAgent has gathered all the needed information, write a good ~200-300 word review in markdown format detailing: \n"
    "    - What is good about the PR? \n"
    "    - Did the author follow ALL contribution rules? What is missing? \n"
    "    - Are there tests for new functionality? If there are new models, are there migrations for them? - use the diff to determine this. \n"
    "    - Are new endpoints documented? - use the diff to determine this. \n"
    "    - Which lines could be improved upon? Quote these lines and offer suggestions the author could implement. \n"
    " - If you need any additional details at any point, you must hand off to the ContextAgent (never to the user). \n"
    " - You should directly address the author. So your comments should sound like: \n"
    ' "Thanks for fixing this. I think all places where we call quote should be fixed. Can you roll this fix out everywhere?" \n'
    " - After saving the draft review with add_comment_to_state, you MUST hand off to the ReviewAndPostingAgent."
)

commentor_agent = FunctionAgent(
    llm=llm,
    name="CommentorAgent",
    description="Uses the context gathered by the context agent to draft a pull review comment.",
    tools=[add_comment_tool],
    system_prompt=COMMENTOR_SYSTEM_PROMPT,
    can_handoff_to=["ContextAgent", "ReviewAndPostingAgent"],
)


# ── ReviewAndPostingAgent ───────────────────────────────────────

REVIEW_AND_POSTING_SYSTEM_PROMPT = (
    "You are the Review and Posting agent. You must use the CommentorAgent to create a review comment. \n"
    "Once a review is generated, you need to run a final check and post it to GitHub.\n"
    "   - The review must: \n"
    "   - Be a ~200-300 word review in markdown format. \n"
    "   - Specify what is good about the PR: \n"
    "   - Did the author follow ALL contribution rules? What is missing? \n"
    "   - Are there notes on test availability for new functionality? If there are new models, are there migrations for them? \n"
    "   - Are there notes on whether new endpoints were documented? \n"
    "   - Are there suggestions on which lines could be improved upon? Are these lines quoted? \n"
    " If the review does not meet this criteria, you must ask the CommentorAgent to rewrite and address these concerns. \n"
    " When you are satisfied, post the review to GitHub."
)

review_and_posting_agent = FunctionAgent(
    llm=llm,
    name="ReviewAndPostingAgent",
    description="Reviews the draft PR comment produced by the CommentorAgent, requests rewrites "
                "if it does not meet the criteria, and posts the final review to GitHub.",
    tools=[add_final_review_tool, post_review_tool],
    system_prompt=REVIEW_AND_POSTING_SYSTEM_PROMPT,
    can_handoff_to=["CommentorAgent"],
)


# ── Workflow ────────────────────────────────────────────────────

workflow_agent = AgentWorkflow(
    agents=[context_agent, commentor_agent, review_and_posting_agent],
    root_agent=review_and_posting_agent.name,
    initial_state={
        "gathered_contexts": "",
        "review_comment": "",
        "final_review": "",
    },
)


# ── Main ────────────────────────────────────────────────────────

async def main():
    query = f"Write a review for PR number {pr_number} and post it to GitHub."
    prompt = RichPromptTemplate(query)

    handler = workflow_agent.run(prompt.format())

    current_agent = None
    async for event in handler.stream_events():
        if hasattr(event, "current_agent_name") and event.current_agent_name != current_agent:
            current_agent = event.current_agent_name
            print(f"Current agent: {current_agent}")
        elif isinstance(event, AgentOutput):
            if event.response.content:
                print("\n\nFinal response:", event.response.content)
            if event.tool_calls:
                print("Selected tools: ", [call.tool_name for call in event.tool_calls])
        elif isinstance(event, ToolCallResult):
            print(f"Output from tool: {event.tool_output}")
        elif isinstance(event, ToolCall):
            print(f"Calling selected tool: {event.tool_name}, with arguments: {event.tool_kwargs}")


if __name__ == "__main__":
    asyncio.run(main())
    git.close()
